[profile.default]
src = "src"
out = "out"
libs = ["lib"]
remappings = [
    '@chainlink/contracts/=lib/chainlink-brownie-contracts/contracts/',
    # D:\dev\defi\rwa-creator\lib\chainlink-brownie-contracts\contracts\src\v0.8\shared\access\ConfirmedOwner.sol
    '@openzeppelin/contracts=lib/openzeppelin-contracts/contracts',
    '@chainlink/contracts-ccip/=lib/ccip-contracts/contracts-ccip/',
]

